LF-Engineering/dev-analytics-affiliation

affiliation/service.go
elastic/service.go
swagger/dev-analytics-affiliation.yaml

This PR adds:
- Github PRs closed
- Github PRs in Open state
- Github Issues Average number of days an Issue is in Open state for an assignee
- Github Issues Assigned to a contributor
- Jira issues closed by a contributor.

DA-1939 add more jira and github fields to contributor summary

---

affiliation/service.go
elastic/service.go
shdb/service.go

@lukaszgryglicki please check out `EnrichContributors` method in the SH service file. I had to comment out 2 lines like this `uuids = append(uuids, projectSlug)` because it was causing the query to fail by adding the project slug to the query arguments.
`
{"level":"warning","msg":"[1:2bc2c020e49b3e6f3d852a2da4dc3594259e5044 2:083aacbaa92a194abf871e11474e5502d6547deb 3:e8c7351c0c434496680117029e59324397a91086 4:947df23087e41cc249b565cf21ff1e8947530904 5:806c186f62c88b4c1cb7638fa2b797428459cd19 6:4afcd6a74c4c03859bb922630c16b93d92141795 7:b84eacefe88202f41d15641f3f549ca8d9f33b6a 8:00e56c226e2b276158873aa2920ba94f19a032c7 9:1d212a13cada8b3d361a422bfb949ec2abb5f9b1 10:693d5b10e08a36cf3d519e6c490b9504a301122a 11:27364b10828a0596f529880000a6b5d333b8cbed …

[PROD] DA-2149 Rearrange data source output for top contributors

---

map_org_names.yaml

Update the organization affiliations for Intel to Intel Corporation

Updating regex for intel

---

map_org_names.yaml

https://jira.linuxfoundation.org/browse/DA-2384

Update Org name from Arris to CommScope Inc.

---

map_org_names.yaml

Added the mapping to merge ```Linux Foundation``` into ```The Linux Foundation```

Updating mapping for Linux Foundation

---

map_org_names.yaml

Merging the names ```Cisco```, ```Cisco System```, ```Cisco Systems Inc. Phone``` and ```CiscoSpark``` into ```Cisco Systems Inc.```

Update mapping for Cisco

---

map_org_names.yaml

Signed-off-by: sgupta <sgupta@linuxfoundation.org>

SUPPORT-2187: ONAP contributions need to be affiliated to 'Samsung'

---

README.md
affiliation/handlers.go
affiliation/service.go
sh/curl_get_identity.sh
swagger/dev-analytics-affiliation.yaml

Add the api to get the identity associated with the uuid.

DA-2501 : Add GetIdentity API 

---

shdb/service.go

Changes Done
- Add two error checks, one for source and other for identity data(email, name, username)
- Add a function to convert the string to "none" if its empty otherwise convert it to lower case.

DA-2501: Fix IdentityIDHash function

---

affiliation/service.go
elastic/service.go
shared/service.go
swagger/dev-analytics-affiliation.yaml

Ref: https://jira.linuxfoundation.org/browse/DA-3055?focusedCommentId=394144&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-394144
Verified Locally.

DA-3055: Add confluence attachment metric to top contributors API & CSV

---

affiliation/service.go
helm/da-affiliation/templates/api.yaml
helm/da-affiliation/templates/secrets.yaml
main.go
platform/organization.go
swagger/dev-analytics-affiliation.yaml

This reverts commit 7344e4af1f3c5aff4c96da73af1e5990bef00798.
Raising this PR to deploy the org service changes on prod.
Related PR - https://github.com/LF-Engineering/dev-analytics-affiliation/pull/49 & https://github.com/LF-Engineering/dev-analytics-affiliation/pull/50

Revert "Revert "DA-3331: org affiliation changes switch list org to use platform service - Part 1 (#49)" (#50)"

---

main.go

updates for test branch to remove the duplicate secret param.

DA-3536:remove duplicate secret param

---

affiliation/service.go
platform/organization.go

Implementing Hybrid solution as suggested by @1010sachin here -
https://jira.linuxfoundation.org/browse/DA-4013?focusedCommentId=532141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-532141
Verified and tested locally.

(test) DA-4013: Update list org api to first lookup and then search org name

---

affiliation/service.go
platform/organization.go

Implementing Hybrid solution as suggested by @1010sachin here -
https://jira.linuxfoundation.org/browse/DA-4013?focusedCommentId=532141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-532141
Verified and tested locally.

(prod) DA-4013: Update list org api to first lookup and then search org name

---

affiliation/handlers.go
affiliation/service.go
shdb/service.go

- Skip disabled projects in APIs
Signed-off-by: linonymous <linonymous@gmail.com>

DA-4598: Skip Disabled Projects

---

affiliation/handlers.go
affiliation/service.go
shdb/service.go

* DA-4538
- Skip disabled projects in APIs
Signed-off-by: linonymous <linonymous@gmail.com>
(cherry picked from commit 009955187a1a181e2b6dc3057cdac66fea04bb87)

[test] DA-4538 - Skip disabled projects in APIs

---

affiliation/handlers.go
affiliation/service.go
shdb/service.go

* DA-4598
- Skip disabled projects in APIs
Signed-off-by: linonymous <linonymous@gmail.com>
(cherry picked from commit 009955187a1a181e2b6dc3057cdac66fea04bb87)

DA-4598: Skip Disabled Projects (#123) (#124)

---

go.mod
go.sum

Raising PR for `test` first
Signed-off-by: Ajinkya Nahar <ajinkyan@proximabiz.com>

DA-4596: update da-lib version for auth0 jwks cache changes

---

go.mod
go.sum

Signed-off-by: Ajinkya Nahar <ajinkyan@proximabiz.com>

DA-4596: update for auth0 jwks cache changes for prod

---

go.mod
go.sum

Signed-off-by: Ajinkya Nahar <ajinkyan@proximabiz.com>

DA-4596: update da-lib version to latest

---

affiliation/service.go
shdb/service.go
sql/add_last_modified_by.sql

DA-4660.
cc @fayazg 
Signed-off-by: Łukasz Gryglicki <lgryglicki@cncf.io>

Add 'last_modified_by' column in affiliations APIs
